### ISSUE TITLE
How did you end up using PHP? 

### ISSUE THREAD

**Issue by jonathanbossenger** [Rarst/AMA#6]
Based on my last question, what lead you to go from qbasic to PHP.

**Comment by Rarst** [comment]
There had been _a lot_ of things between qbasic and PHP: Turbo Pascal, C, C++, EasyUO, AutoIt, Perl...

I don’t remember when and how I picked up PHP exactly, but I used Perl before it and I while I liked writeability, it critically lacked in readability. Simply put I enjoyed writing Perl, but three days later I could never read what I wrote.

I don’t remember what the earliest personal use of PHP was, but earliest professional use I remember being building some custom reporting for support system I was running. It was already web based, but not directly extensible (Java app w/ embedded web server). PHP allowed to easily build some web additions, getting data out of its database and graphing it in browser.

I think the closest competition was Python, but PHP seemed a little more popular and easy to pick up.
